# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate wayrs-protocols

Name:           rust-wayrs-protocols
Version:        0.14.0
Release:        %autorelease
Summary:        Collection of Wayland protocols to use with wayrs-client

License:        MIT
URL:            https://crates.io/crates/wayrs-protocols
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A collection of Wayland protocols to use with wayrs-client.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/wayland-protocols/COPYING
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alpha-modifier-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alpha-modifier-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "alpha-modifier-v1" feature of the "%{crate}" crate.

%files       -n %{name}+alpha-modifier-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+content-type-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+content-type-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "content-type-v1" feature of the "%{crate}" crate.

%files       -n %{name}+content-type-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cursor-shape-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cursor-shape-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "cursor-shape-v1" feature of the "%{crate}" crate.

%files       -n %{name}+cursor-shape-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+drm-lease-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+drm-lease-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "drm-lease-v1" feature of the "%{crate}" crate.

%files       -n %{name}+drm-lease-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ext-foreign-toplevel-list-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ext-foreign-toplevel-list-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "ext-foreign-toplevel-list-v1" feature of the "%{crate}" crate.

%files       -n %{name}+ext-foreign-toplevel-list-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ext-idle-notify-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ext-idle-notify-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "ext-idle-notify-v1" feature of the "%{crate}" crate.

%files       -n %{name}+ext-idle-notify-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ext-session-lock-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ext-session-lock-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "ext-session-lock-v1" feature of the "%{crate}" crate.

%files       -n %{name}+ext-session-lock-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ext-transient-seat-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ext-transient-seat-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "ext-transient-seat-v1" feature of the "%{crate}" crate.

%files       -n %{name}+ext-transient-seat-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fractional-scale-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fractional-scale-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "fractional-scale-v1" feature of the "%{crate}" crate.

%files       -n %{name}+fractional-scale-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fullscreen-shell-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fullscreen-shell-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "fullscreen-shell-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+fullscreen-shell-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+idle-inhibit-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+idle-inhibit-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "idle-inhibit-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+idle-inhibit-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+input-method-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+input-method-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "input-method-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+input-method-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+input-timestamps-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+input-timestamps-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "input-timestamps-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+input-timestamps-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+keyboard-shortcuts-inhibit-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+keyboard-shortcuts-inhibit-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "keyboard-shortcuts-inhibit-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+keyboard-shortcuts-inhibit-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+linux-dmabuf-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+linux-dmabuf-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "linux-dmabuf-v1" feature of the "%{crate}" crate.

%files       -n %{name}+linux-dmabuf-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+linux-drm-syncobj-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+linux-drm-syncobj-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "linux-drm-syncobj-v1" feature of the "%{crate}" crate.

%files       -n %{name}+linux-drm-syncobj-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+linux-explicit-synchronization-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+linux-explicit-synchronization-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "linux-explicit-synchronization-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+linux-explicit-synchronization-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pointer-constraints-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pointer-constraints-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "pointer-constraints-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+pointer-constraints-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pointer-gestures-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pointer-gestures-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "pointer-gestures-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+pointer-gestures-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+presentation-time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+presentation-time-devel %{_description}

This package contains library source intended for building other packages which
use the "presentation-time" feature of the "%{crate}" crate.

%files       -n %{name}+presentation-time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+primary-selection-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+primary-selection-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "primary-selection-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+primary-selection-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+relative-pointer-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+relative-pointer-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "relative-pointer-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+relative-pointer-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+security-context-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+security-context-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "security-context-v1" feature of the "%{crate}" crate.

%files       -n %{name}+security-context-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+single-pixel-buffer-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+single-pixel-buffer-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "single-pixel-buffer-v1" feature of the "%{crate}" crate.

%files       -n %{name}+single-pixel-buffer-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tablet-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tablet-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "tablet-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+tablet-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tablet-v2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tablet-v2-devel %{_description}

This package contains library source intended for building other packages which
use the "tablet-v2" feature of the "%{crate}" crate.

%files       -n %{name}+tablet-v2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tearing-control-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tearing-control-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "tearing-control-v1" feature of the "%{crate}" crate.

%files       -n %{name}+tearing-control-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-input-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+text-input-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "text-input-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+text-input-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-input-unstable-v3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+text-input-unstable-v3-devel %{_description}

This package contains library source intended for building other packages which
use the "text-input-unstable-v3" feature of the "%{crate}" crate.

%files       -n %{name}+text-input-unstable-v3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+viewporter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+viewporter-devel %{_description}

This package contains library source intended for building other packages which
use the "viewporter" feature of the "%{crate}" crate.

%files       -n %{name}+viewporter-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-data-control-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-data-control-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-data-control-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-data-control-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-export-dmabuf-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-export-dmabuf-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-export-dmabuf-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-export-dmabuf-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-foreign-toplevel-management-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-foreign-toplevel-management-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-foreign-toplevel-management-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-foreign-toplevel-management-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-gamma-control-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-gamma-control-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-gamma-control-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-gamma-control-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-input-inhibitor-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-input-inhibitor-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-input-inhibitor-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-input-inhibitor-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-layer-shell-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-layer-shell-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-layer-shell-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-layer-shell-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-output-management-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-output-management-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-output-management-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-output-management-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-output-power-management-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-output-power-management-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-output-power-management-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-output-power-management-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-screencopy-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-screencopy-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-screencopy-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-screencopy-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wlr-virtual-pointer-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wlr-virtual-pointer-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "wlr-virtual-pointer-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+wlr-virtual-pointer-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-activation-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-activation-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-activation-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-activation-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-decoration-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-decoration-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-decoration-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-decoration-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-dialog-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-dialog-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-dialog-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-dialog-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-foreign-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-foreign-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-foreign-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-foreign-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-foreign-unstable-v2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-foreign-unstable-v2-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-foreign-unstable-v2" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-foreign-unstable-v2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-output-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-output-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-output-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-output-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-shell-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-shell-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-shell" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-shell-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-shell-unstable-v5-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-shell-unstable-v5-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-shell-unstable-v5" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-shell-unstable-v5-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-shell-unstable-v6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-shell-unstable-v6-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-shell-unstable-v6" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-shell-unstable-v6-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xdg-toplevel-drag-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xdg-toplevel-drag-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xdg-toplevel-drag-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xdg-toplevel-drag-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xwayland-keyboard-grab-unstable-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xwayland-keyboard-grab-unstable-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xwayland-keyboard-grab-unstable-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xwayland-keyboard-grab-unstable-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+xwayland-shell-v1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+xwayland-shell-v1-devel %{_description}

This package contains library source intended for building other packages which
use the "xwayland-shell-v1" feature of the "%{crate}" crate.

%files       -n %{name}+xwayland-shell-v1-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
